version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGO_URL: mongodb://database:27017/mydb
    depends_on:
      - database
    command: npm run dev

  database:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db